<a href="https://colab.research.google.com/github/nitron-alpha-kplr/Reinforcement-Learning/blob/main/Workshop_Frozen_Lake_Solution.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Workshop : Frozen Lake - Solution

Q* Learning with FrozenLake 4x4
In this Notebook, we'll implement an agent that plays FrozenLake.




The goal of this game is to go from the starting state (S) to the goal state (G) by walking only on frozen tiles (F) and avoid holes (H). However, the ice is slippery, so you won't always move in the direction you intend (stochastic environment)

Prerequisites ️
Before diving on the notebook you need to understand:

The foundations of Reinforcement learning (MC, TD, Rewards hypothesis...) Article
Q-learning Article
In the video version we implemented a Q-learning agent that learns to play OpenAI Taxi-v2 with Numpy.

In [1]:
!pip install numpy
!pip install gym==0.7.4.

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 152.2/152.2 kB 3.3 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 841.0/841.0 kB 21.2 MB/s eta 0:00:00
  Created wheel for gym: filename=gym-0.7.4-py3-none-any.whl size=204668 sha256=91ffa8778facb035057005a753f1c907338efb46eb6c8f12f847922cebc54efb
  Stored in directory: /root/.cache/pip/wheels/de/55/26/d9b9f975bc80a53913520dd7ded672660cf82a01ac3b0a8769
Successfully built gym
  Attempting uninstall: gym
    Found existing installation: gym 0.25.2
    Uninstalling gym-0.25.2:
      Successfully uninstalled gym-0.25.2


In [3]:
#import the required libraries.
import numpy as np
import gym
import random
#create the environment usign OpenAI Gym
env = gym.make("FrozenLake-v0")


INFO:gym.envs.registration:Making new env: FrozenLake-v0
[2023-06-22 08:04:44,436] Making new env: FrozenLake-v0
/usr/local/lib/python3.10/dist-packages/gym/envs/registration.py:17: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


Step 2:  Create the Q-table and initialize it

In [5]:
action_size = env.action_space.n
state_size = env.observation_space.n

print(f"Action Space : {action_size} | State Space: {state_size}")

Action Space : 4 | State Space: 16


In [6]:
qtable = np.zeros((state_size, action_size))
print(qtable.shape)

(16, 4)


Step 2:  Create the Q-table and initialize it

In [8]:
total_episodes = 15000        # Total episodes
learning_rate = 0.8           # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.95                  # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability
decay_rate = 0.005             # Exponential decay rate for exploration prob

Step 4 : Q-Learning Algorithm

In [9]:
# List of rewards
rewards = []

#until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        #Choose an action a in the current world state (s)
        exp_exp_tradeoff = random.uniform(0, 1)

        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] + learning_rate * \
                                                        (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])

        total_rewards += reward

        # Our new state is state
        state = new_state

        # If done (if we're dead) : finish episode
        if done == True:
            break

    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon) * np.exp(-decay_rate * episode)

    rewards.append(total_rewards)

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.48486666666666667
[[2.78505243e-01 8.01246530e-02 3.53051296e-02 8.23637021e-02]
 [3.65954843e-02 4.81971049e-02 6.71212767e-03 1.74387491e-01]
 [4.10808519e-03 4.62863024e-02 3.52806713e-02 1.63100538e-01]
 [1.47182145e-04 2.45615459e-02 1.24188751e-02 7.50735114e-02]
 [3.00536755e-01 1.01330607e-02 2.81851501e-02 3.63119797e-02]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.79109591e-04 2.15700028e-04 8.65869253e-03 8.96046995e-06]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [3.05883065e-03 6.65513988e-02 3.14000180e-02 5.48654176e-01]
 [4.14922794e-03 5.86043640e-01 1.96043163e-03 1.00408392e-02]
 [1.66319776e-01 7.32941217e-04 5.42433654e-03 6.17749811e-04]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [7.99296156e-02 1.13922996e-01 8.76559461e-01 9.42495679e-02]
 [2.03797095e-01 9.98960823e-01 1.48995506e-01 1.95286040e-01]
 [0.00000000e+00 0

In [10]:
for episode in range(5):
    state = env.reset()
    step = 0
    done = False
    print("****************************************************")
    print("EPISODE ", episode)

    for step in range(max_steps):

        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])

        new_state, reward, done, info = env.step(action)

        if done:
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()

            # We print the number of step it took.
            print("Number of steps", step)
            break
        state = new_state
env.close()

****************************************************
EPISODE  0
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 16
****************************************************
EPISODE  1
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 25
****************************************************
EPISODE  2
****************************************************
EPISODE  3
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 21
****************************************************
EPISODE  4
  (Down)
SFFF
FHFH
FFFH
HFFG
Number of steps 26


In [11]:
print("Système de récompense :")
for state in range(env.env.nS):
    for action in range(env.env.nA):
        transitions = env.env.P[state][action]
        for prob, next_state, reward, _ in transitions:
            print(f"État {state}, Action {action}, État suivant {next_state} : {reward}")

Système de récompense :
État 0, Action 0, État suivant 0 : 0.0
État 0, Action 0, État suivant 0 : 0.0
État 0, Action 0, État suivant 4 : 0.0
État 0, Action 1, État suivant 0 : 0.0
État 0, Action 1, État suivant 4 : 0.0
État 0, Action 1, État suivant 1 : 0.0
État 0, Action 2, État suivant 4 : 0.0
État 0, Action 2, État suivant 1 : 0.0
État 0, Action 2, État suivant 0 : 0.0
État 0, Action 3, État suivant 1 : 0.0
État 0, Action 3, État suivant 0 : 0.0
État 0, Action 3, État suivant 0 : 0.0
État 1, Action 0, État suivant 1 : 0.0
État 1, Action 0, État suivant 0 : 0.0
État 1, Action 0, État suivant 5 : 0.0
État 1, Action 1, État suivant 0 : 0.0
État 1, Action 1, État suivant 5 : 0.0
État 1, Action 1, État suivant 2 : 0.0
État 1, Action 2, État suivant 5 : 0.0
État 1, Action 2, État suivant 2 : 0.0
État 1, Action 2, État suivant 1 : 0.0
État 1, Action 3, État suivant 2 : 0.0
État 1, Action 3, État suivant 1 : 0.0
État 1, Action 3, État suivant 0 : 0.0
État 2, Action 0, État suivant 2 : 0.0
É